CREATE TABLE LOG_MOVIMIENTOS_PRODUCTOS (
    ID_Log INT PRIMARY KEY AUTO_INCREMENT,
    ID_Registro_Afectado INT NOT NULL,
    Tabla_Afectada VARCHAR(255) NOT NULL,
    Usuario VARCHAR(255) NOT NULL,
    Fecha DATE NOT NULL,
    Hora TIME NOT NULL,
    Operacion VARCHAR(50) NOT NULL
);

CREATE TABLE LOG_MOVIMIENTOS_CLIENTES (
    ID_Log INT PRIMARY KEY AUTO_INCREMENT,
    ID_Registro_Afectado INT NOT NULL,
    Tabla_Afectada VARCHAR(255) NOT NULL,
    Usuario VARCHAR(255) NOT NULL,
    Fecha DATE NOT NULL,
    Hora TIME NOT NULL,
    Operacion VARCHAR(50) NOT NULL
);