CREATE TRIGGER After_LogMovimientosProductos
AFTER INSERT ON LOG_MOVIMIENTOS_PRODUCTOS
FOR EACH ROW
BEGIN
   
END;

CREATE TRIGGER After_LogMovimientosClientes
AFTER INSERT ON LOG_MOVIMIENTOS_CLIENTES
FOR EACH ROW
BEGIN
   
END;