CREATE TRIGGER Before_LogMovimientosProductos
BEFORE INSERT ON LOG_MOVIMIENTOS_PRODUCTOS
FOR EACH ROW
SET NEW.Fecha = COALESCE(NEW.Fecha, CURDATE()), NEW.Hora = COALESCE(NEW.Hora, CURTIME());

CREATE TRIGGER Before_LogMovimientosClientes
BEFORE INSERT ON LOG_MOVIMIENTOS_CLIENTES
FOR EACH ROW
SET NEW.Fecha = COALESCE(NEW.Fecha, CURDATE()), NEW.Hora = COALESCE(NEW.Hora, CURTIME());